### ISSUE TITLE
Support npm namespaces

### ISSUE THREAD

**Issue by asg017** [asg017/sqlite-dist#14]
[scoped npm packages](https://docs.npmjs.com/cli/v8/using-npm/scope). Maybe a new `npm.scope` option in `sqlite-dist.toml`?

```toml
name = "sqlite-foo"

[[targets]]
npm = {scope="orbitinghail"}
```
